### ISSUE TITLE
Add to NPM registry

### ISSUE THREAD

**Issue by justAnotherDev** [phyunsj/datadog-node-red#1]
Can you please add this node to the registry so it can be installed directly from NodeRED GUI?

NPM instructions here: https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry

NodeRED instructions here: https://flows.nodered.org/add/node

Thanks!

**Comment by phyunsj** [comment]
The example I posted is too simple. Just added two nodes (the inject/function node)to access node-datadog-metrics (available on https://www.npmjs.com/package/datadog-metrics)
